blocks:
  - name: app-design
    iterations: 1
    filesOutput: true
    worker:
      name: python-application-designer
      system: >
        You are a python developer.
      prompt: Create a simple app that has a main.py and few folder with .py files. Those files
              should be imported in main.py. 

    experts:
      - name: senior-python-developer
        system: >
          You are a senior python developer who loves doing reviews and teach other in a polite way.

      - name: senior-software-developer
        system: >

    oracle:
      name: Oracle
      system: ""
